#!/bin/bash
#!/usr/bin/env bash
openssl req -x509 -newkey rsa:2048 -keyout key.pem -out cert.pem -days 9125 -nodes


# Country Name (2 letter code) []:IN
# State or Province Name (full name) []:Karnataka
# Locality Name (eg, city) []:Bangalore
# Organization Name (eg, company) []:Cloudparker
# Organizational Unit Name (eg, section) []:IT
# Common Name (eg, fully qualified host name) []:localhost
# Email Address []:support@cloudparker.com

# npm run dev
# open https://localhost:44301/ in chrome
# Allow https security check...