#!/bin/bash
#!/usr/bin/env bash
openssl req -x509 -newkey rsa:2048 -keyout key.pem -out cert.pem -days 9125 -nodes \
  -subj "/C=IN/ST=Karnataka/L=Bangalore/O=Cloudparker/OU=IT/CN=localhost/emailAddress=support@cloudparker.com" \
  -addext "subjectAltName=DNS:localhost"


# Country Name (2 letter code) []:IN
# State or Province Name (full name) []:Karnataka
# Locality Name (eg, city) []:Bangalore
# Organization Name (eg, company) []:Cloudparker
# Organizational Unit Name (eg, section) []:IT
# Common Name (eg, fully qualified host name) []:localhost
# Email Address []:support@cloudparker.com

# npm run dev
# open https://localhost:44301/ in chrome
# Allow https security check...


# MAKE TRUST THE CERTIFICATE
# Import the certificate to Keychain Access (Mac):
# Open Keychain Access (Applications > Utilities > Keychain Access).
# Drag and drop the cert.pem file into the System or Login keychain.
# Double-click the certificate in Keychain Access.
# Expand the Trust section, and set When using this certificate to Always Trust.
# Close the window and enter your Mac password to apply the changes.